In [ ]:
# installing catboost library
!pip install catboost

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.5/98.5 MB 8.9 MB/s eta 0:00:00


In [ ]:
# importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, recall_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import make_scorer, precision_score, recall_score, f1_score
from sklearn.model_selection import cross_validate
from sklearn.naive_bayes import CategoricalNB
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC

from sklearn.metrics import accuracy_score

from sklearn import metrics as mt
import matplotlib.pyplot as plt
import warnings
import sys
warnings.filterwarnings('ignore')

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_validate, StratifiedKFold
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from catboost import CatBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.decomposition import PCA
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score

# **ML**

In [ ]:
# loading features from pFeature
aac = pd.read_csv("/content/drive/MyDrive/AAC_feature.csv")
dpc = pd.read_csv("/content/drive/MyDrive/DPC_feature.csv")
struct_pc = pd.read_csv("/content/drive/MyDrive/final_physico-chemical_result_structural.csv")
target = pd.read_csv("/content/drive/MyDrive/target.csv")

In [ ]:
struct_pc = struct_pc.drop(['ID'],axis=1) # removing unnecessary column

In [ ]:
struct_pc # displaying the data

PCP_PC  PCP_PO  PCP_NP  PCP_AL  PCP_CY  PCP_AR  PCP_AC  PCP_BS  PCP_HB  \
0       0.200   0.200   0.467   0.400   0.000   0.000   0.133   0.200   0.467   
1       0.267   0.267   0.467   0.400   0.000   0.000   0.000   0.267   0.533   
2       0.200   0.133   0.467   0.400   0.000   0.067   0.133   0.200   0.400   
3       0.267   0.200   0.333   0.333   0.000   0.000   0.200   0.267   0.467   
4       0.200   0.133   0.533   0.533   0.000   0.067   0.067   0.200   0.467   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
62164   0.200   0.267   0.533   0.533   0.133   0.000   0.000   0.200   0.467   
62165   0.133   0.200   0.533   0.533   0.067   0.000   0.133   0.133   0.667   
62166   0.133   0.267   0.533   0.533   0.133   0.067   0.067   0.133   0.400   
62167   0.067   0.267   0.333   0.333   0.000   0.133   0.200   0.067   0.333   
62168   0.133   0.200   0.667   0.533   0.067   0.200   0.000   0.133   0.667   

       PCP_HL  PCP_SC  PCP_SM  PCP_LR  
0       0.200   0.067   0.533   0.467  
1       0.267   0.067   0.533   0.467  
2       0.267   0.000   0.533   0.467  
3       0.267   0.000   0.400   0.600  
4       0.267   0.000   0.667   0.333  
...       ...     ...     ...     ...  
62164   0.333   0.067   0.733   0.267  
62165   0.200   0.067   0.533   0.467  
62166   0.267   0.000   0.600   0.400  
62167   0.200   0.000   0.533   0.467  
62168   0.200   0.000   0.400   0.600  

[62169 rows x 13 columns]

In [ ]:
# combined featues of amino acid composition, dipeptide composition and physio-chemical properties
# pca decomposition for extracting relevant features
x = pd.concat([aac,dpc,struct_pc], axis=1)
pca = PCA(n_components = 20)
pca.fit(x)
x = pca.transform(x)
#x = aac.copy()
#x = dpc.copy() # dipeptide composition
y = target['Target']

In [ ]:
# converting the dataset to dataframe
merged = pd.DataFrame(x)
merged

0          1         2          3          4          5   \
0     -13.053715   3.790318  8.065266  -0.043000  -0.054886  -0.667484   
1      -7.358935   8.338863  2.751953   6.658195   8.997579   3.672865   
2      -7.054218  -1.221625  3.427780   9.302756   8.411355  -2.870448   
3      -9.169274  -8.145787 -3.807463   4.461450   9.030827  -2.642917   
4      -5.861123   6.899168  6.824510   0.522293  13.682671 -11.828409   
...          ...        ...       ...        ...        ...        ...   
62164  11.540261   7.751588  1.747371  -3.806383  -2.125845   0.563583   
62165  -6.558874  -0.816402 -5.745638  -4.847332  12.748035  -8.062734   
62166  -3.728998  10.929366  5.393242  -0.960134 -15.534516   1.611601   
62167  -8.314587 -10.199028  5.766962  -3.327338  -1.366699   5.935977   
62168  -7.107357   1.014807 -0.250311 -10.346242  14.902254  -1.071557   

              6          7         8          9         10        11  \
0       7.380616   1.519701  0.231986   6.013242 -5.587439  7.595682   
1       7.277649 -12.088634 -8.652721  -0.622383 -2.592830  3.977694   
2      -7.584587  -9.095440 -1.350147  -0.196390 -2.915542  5.641263   
3       5.757713   1.172899 -8.090231  -6.047554 -8.423667 -2.276254   
4       3.102521 -12.947490  8.086748  11.052400 -5.342449 -0.773831   
...          ...        ...       ...        ...       ...       ...   
62164  -8.761624  -4.196561  0.425722  10.018049 -4.624379 -0.705497   
62165   0.472373   3.399214  2.658550   2.177471 -3.523028 -5.569266   
62166  -1.208039   2.984913  3.259484   9.167431  7.959095 -0.120992   
62167  -1.935288   2.644726  9.939634  -2.539245  3.017983 -5.847553   
62168 -10.698388   5.645436 -5.822087  -2.742076 -3.237875 -2.019742   

             12        13        14        15         16        17        18  \
0     -2.353849 -0.920978  4.320995  2.866698   0.915607  5.726207 -0.645284   
1     -5.568341 -1.350038  1.180296 -0.698333   0.243506  5.935766 -0.882405   
2     -0.014968  6.647411 -0.783774  3.352603  -2.539775 -2.116922 -0.317005   
3     -4.721682 -1.392506  2.240209 -0.528619  -0.909605 -1.388254  0.310112   
4      4.948563  2.000013  4.679590 -2.184099  -1.997017 -1.294524 -0.454034   
...         ...       ...       ...       ...        ...       ...       ...   
62164 -0.212298 -1.560425 -0.313470  1.343365   6.266208 -1.841845  5.091438   
62165 -4.158537 -2.671293  0.980686 -0.163941  -0.971046 -0.304007  7.381124   
62166  0.270428 -6.159607 -1.356217 -0.540130  10.412351 -4.399367 -2.548351   
62167  8.414902  2.653035  6.632082 -4.674728  -2.669153 -2.431772 -1.074895   
62168  6.636363 -3.991274 -3.547529  3.234680  -3.718718 -1.571904 -0.012909   

             19  
0      1.817404  
1      0.156351  
2      0.082921  
3      0.610095  
4     -0.122382  
...         ...  
62164 -1.896415  
62165 -1.214969  
62166 -2.036092  
62167  1.109678  
62168 -0.128044  

[62169 rows x 20 columns]

In [ ]:
# function to evaluate score with k fold cross validation
def print_metrics(clf, x, y, cv):
  scoring = {
      'precision': make_scorer(precision_score),
      'recall': make_scorer(recall_score),
      'f1_score': make_scorer(f1_score)
  }
  cross_val_results = cross_validate(clf, x, y, cv=cv, scoring = scoring)
  accuracy = cross_val_score(clf, x, y, cv=cv, scoring = 'f1_macro')
  print("Average Precision:", cross_val_results['test_precision'].mean())
  print("Average Recall:", cross_val_results['test_recall'].mean())
  print("Average F1 Score:", cross_val_results['test_f1_score'].mean())
  print("Average Accuracy Score:", accuracy.mean())

In [ ]:
# function to print evaluation metrices
def metric_calculation(y_test,y_pred):
  print("Accuracy  :  ",mt.accuracy_score(y_test,y_pred))
  print("Precision :  ",mt.precision_score(y_test,y_pred))
  print("Recall    :  ",mt.recall_score(y_test,y_pred))
  print("F1-score  :  ",mt.f1_score(y_test,y_pred))
  print("Confusion matrix      : \n ",mt.confusion_matrix(y_test,y_pred))
  print("Classification report : \n",mt.classification_report(y_test,y_pred))

In [ ]:
# creating objects of classifiers
clf= RandomForestClassifier()
clf_str= RandomForestClassifier()
rf = RandomForestClassifier()
nb = MultinomialNB()
mlp = MLPClassifier()
sgd = SGDClassifier()
svc = SVC()
lr = LogisticRegression()
knn = KNeighborsClassifier(n_neighbors=3)
cat = CatBoostClassifier( iterations=100, depth=6, learning_rate=0.1,verbose=False)
bgc_rf = BaggingClassifier(estimator=rf, n_estimators=10, random_state=0)
hist_gbc = HistGradientBoostingClassifier()
ada = AdaBoostClassifier(base_estimator=rf, n_estimators=10, learning_rate = 0.1)
lgbm = LGBMClassifier(random_state=5)

In [ ]:
# creating objects of k fold and stratified k fold
num_folds = 10
kf = KFold(n_splits=num_folds, shuffle=True, random_state=42)
str_kf = StratifiedKFold(n_splits=num_folds, shuffle=True, random_state=42)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1) # splitting the data into train test

In [ ]:
print_metrics(clf, x, y, kf) # Random Forest with 10 fold cv

In [ ]:
print_metrics(clf_str, x, y, str_kf) # Random Forest with stratified 10 fold cv

Average Precision: 0.7856780789978108
Average Recall: 0.8303022596838623
Average F1 Score: 0.8073397960183415
Average Accuracy Score: 0.7952656474919089


In [ ]:
# print_metrics(nb, x, y, kf) # Naive Bayes with 10 fold cv

In [ ]:
# print_metrics(nb, x, y, str_kf) # Naive Byes with stratified 10 fold cv

In [ ]:
print_metrics(mlp, x, y, kf) # MLP with 10 fold cv

Average Precision: 0.6909062732454629
Average Recall: 0.708595820778537
Average F1 Score: 0.6985297172101168
Average Accuracy Score: 0.6858919820264504


In [ ]:
print_metrics(sgd, x, y, kf) # SGD with 10 fold cv

Average Precision: 0.6295562327537744
Average Recall: 0.6513773013712421
Average F1 Score: 0.6023229636713112
Average Accuracy Score: 0.6022769290407799


In [ ]:
# print_metrics(svc, x, y, kf)

In [ ]:
print_metrics(lr, x, y, kf) # logistic regression with 10 fold cv

Average Precision: 0.6508640888403017
Average Recall: 0.7088535524544917
Average F1 Score: 0.6785557041369901
Average Accuracy Score: 0.6502510409589618


In [ ]:
print_metrics(lr, x, y, str_kf) # logistic regression with stratified 10 fold cv

Average Precision: 0.651032377153191
Average Recall: 0.7095030365734276
Average F1 Score: 0.6789905197650721
Average Accuracy Score: 0.6505158826530592


In [ ]:
print_metrics(knn, x, y, kf) # knn with  10 fold cv and k=3

Average Precision: 0.7054014035701813
Average Recall: 0.7897369236537253
Average F1 Score: 0.7451568696082238
Average Accuracy Score: 0.7178444689763765


In [ ]:
print_metrics(knn, x, y, str_kf) # knn with stratified 10 fold cv and k=3

Average Precision: 0.7020738627497837
Average Recall: 0.7879634408776758
Average F1 Score: 0.7425227513130714
Average Accuracy Score: 0.7144520054490711


In [ ]:
print_metrics(cat, x, y, kf) # cataboost with  10 fold cv

Average Precision: 0.6770037991662095
Average Recall: 0.7394949194039985
Average F1 Score: 0.7068112992936924
Average Accuracy Score: 0.6804089716392252


In [ ]:
print_metrics(cat, x, y, str_kf) # cataboost with stratified 10 fold cv

Average Precision: 0.6764225658365177
Average Recall: 0.739345431685217
Average F1 Score: 0.7064687741971329
Average Accuracy Score: 0.6798348579213274


In [ ]:
print_metrics(hist_gbc, x, y, kf) # hist_gbc with  10 fold cv

Average Precision: 0.6847214067355389
Average Recall: 0.750598477792656
Average F1 Score: 0.7160876337926089
Average Accuracy Score: 0.6895094866634953


In [ ]:
print_metrics(hist_gbc, x, y, str_kf) # hist_gbc with stratified 10 fold cv

Average Precision: 0.6841744808040541
Average Recall: 0.7476453507253908
Average F1 Score: 0.7144833998903626
Average Accuracy Score: 0.6897624314601423


In [ ]:
# train test split with naive bayes
nb.fit(x_train,y_train)
y_pred = nb.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6591067503082945
Precision :   0.6568088033012379
Recall    :   0.7
F1-score  :   0.6777169505271694
Confusion matrix      : 
  [[5608 3493]
 [2865 6685]]
Classification report : 
               precision    recall  f1-score   support

           0       0.66      0.62      0.64      9101
           1       0.66      0.70      0.68      9550

    accuracy                           0.66     18651
   macro avg       0.66      0.66      0.66     18651
weighted avg       0.66      0.66      0.66     18651



In [ ]:
# train test split with random forest
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.7792611656211463
Precision :   0.7658283589392308
Recall    :   0.8194764397905759
F1-score  :   0.7917446507157672
Confusion matrix      : 
  [[6708 2393]
 [1724 7826]]
Classification report : 
               precision    recall  f1-score   support

           0       0.80      0.74      0.77      9101
           1       0.77      0.82      0.79      9550

    accuracy                           0.78     18651
   macro avg       0.78      0.78      0.78     18651
weighted avg       0.78      0.78      0.78     18651



In [ ]:
# train test split with logistic regression
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6541740389255268
Precision :   0.6461712561297623
Recall    :   0.7174869109947644
F1-score  :   0.6799642750818696
Confusion matrix      : 
  [[5349 3752]
 [2698 6852]]
Classification report : 
               precision    recall  f1-score   support

           0       0.66      0.59      0.62      9101
           1       0.65      0.72      0.68      9550

    accuracy                           0.65     18651
   macro avg       0.66      0.65      0.65     18651
weighted avg       0.66      0.65      0.65     18651



In [ ]:
# train test split with mlp
mlp.fit(x_train,y_train)
y_pred = mlp.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6792665272639536
Precision :   0.7024971623155505
Recall    :   0.6480628272251309
F1-score  :   0.6741830065359476
Confusion matrix      : 
  [[6480 2621]
 [3361 6189]]
Classification report : 
               precision    recall  f1-score   support

           0       0.66      0.71      0.68      9101
           1       0.70      0.65      0.67      9550

    accuracy                           0.68     18651
   macro avg       0.68      0.68      0.68     18651
weighted avg       0.68      0.68      0.68     18651



In [ ]:
# train test split with svm
# svc.fit(x_train,y_train)
# y_pred = svc.predict(x_test)
# metric_calculation(y_test,y_pred)

In [ ]:
# train test split with sgd
sgd.fit(x_train,y_train)
y_pred = sgd.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6235054420674495
Precision :   0.618596359542128
Recall    :   0.6903664921465968
F1-score  :   0.652513855898654
Confusion matrix      : 
  [[5036 4065]
 [2957 6593]]
Classification report : 
               precision    recall  f1-score   support

           0       0.63      0.55      0.59      9101
           1       0.62      0.69      0.65      9550

    accuracy                           0.62     18651
   macro avg       0.62      0.62      0.62     18651
weighted avg       0.62      0.62      0.62     18651



In [ ]:
# train test split with knn with k=3
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.7085410969921184
Precision :   0.6913132440476191
Recall    :   0.7783246073298429
F1-score  :   0.7322431287557877
Confusion matrix      : 
  [[5782 3319]
 [2117 7433]]
Classification report : 
               precision    recall  f1-score   support

           0       0.73      0.64      0.68      9101
           1       0.69      0.78      0.73      9550

    accuracy                           0.71     18651
   macro avg       0.71      0.71      0.71     18651
weighted avg       0.71      0.71      0.71     18651



In [ ]:
# train test split with catabbost
cat.fit(x_train,y_train)
y_pred = cat.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6844137043590156
Precision :   0.6733207190160833
Recall    :   0.7452356020942409
F1-score  :   0.7074552683896621
Confusion matrix      : 
  [[5648 3453]
 [2433 7117]]
Classification report : 
               precision    recall  f1-score   support

           0       0.70      0.62      0.66      9101
           1       0.67      0.75      0.71      9550

    accuracy                           0.68     18651
   macro avg       0.69      0.68      0.68     18651
weighted avg       0.69      0.68      0.68     18651



In [ ]:
# train test split with bagging classifier
bgc_rf.fit(x_train,y_train)
y_pred = bgc_rf.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.7701999892767144
Precision :   0.7489595157018539
Recall    :   0.829109947643979
F1-score  :   0.7869993042441109
Confusion matrix      : 
  [[6447 2654]
 [1632 7918]]
Classification report : 
               precision    recall  f1-score   support

           0       0.80      0.71      0.75      9101
           1       0.75      0.83      0.79      9550

    accuracy                           0.77     18651
   macro avg       0.77      0.77      0.77     18651
weighted avg       0.77      0.77      0.77     18651



In [ ]:
# train test split with Hist Gradient Boosting Classifier
hist_gbc.fit(x_train,y_train)
y_pred = hist_gbc.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6920808535735349
Precision :   0.68
Recall    :   0.7529842931937173
F1-score  :   0.7146335403726708
Confusion matrix      : 
  [[5717 3384]
 [2359 7191]]
Classification report : 
               precision    recall  f1-score   support

           0       0.71      0.63      0.67      9101
           1       0.68      0.75      0.71      9550

    accuracy                           0.69     18651
   macro avg       0.69      0.69      0.69     18651
weighted avg       0.69      0.69      0.69     18651



In [ ]:
# train test split with Hist AdaBoost Classifier
ada.fit(x_train,y_train)
y_pred = ada.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.7811913570317945
Precision :   0.7619503783887346
Recall    :   0.8328795811518325
F1-score  :   0.7958377107409076
Confusion matrix      : 
  [[6616 2485]
 [1596 7954]]
Classification report : 
               precision    recall  f1-score   support

           0       0.81      0.73      0.76      9101
           1       0.76      0.83      0.80      9550

    accuracy                           0.78     18651
   macro avg       0.78      0.78      0.78     18651
weighted avg       0.78      0.78      0.78     18651



In [ ]:
# train test split with Hist LGBM  Classifier
lgbm.fit(x_train,y_train)
y_pred = lgbm.predict(x_test)
metric_calculation(y_test,y_pred)

[LightGBM] [Info] Number of positive: 22619, number of negative: 20899
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.035041 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 222
[LightGBM] [Info] Number of data points in the train set: 43518, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.519762 -> initscore=0.079089
[LightGBM] [Info] Start training from score 0.079089
Accuracy  :   0.6910085250120637
Precision :   0.6786152249787756
Recall    :   0.7532984293193717
F1-score  :   0.7140092303111507
Confusion matrix      : 
  [[5694 3407]
 [2356 7194]]
Classification report : 
               precision    recall  f1-score   support

           0       0.71      0.63      0.66      9101
           1       0.68      0.75      0.71      9550

    accuracy                           0.69     18651
   macro avg   

In [ ]:
# defining the estimators
estimator = []
estimator.append(('CLF',  clf))
estimator.append(('CLF_STR', clf_str))
estimator.append(('RF', rf))

In [ ]:
# applying voting classifier with best estimators
vot_hard = VotingClassifier(estimators = estimator, voting ='soft')
vot_hard.fit(x_train, y_train)
y_pred = vot_hard.predict(x_test)

In [ ]:
print(classification_report(y_test, y_pred)) # displaying the evaluation scores

In [ ]:
# checking the evaluation scores with cv=13
c = []
c.append(cross_val_score(clf,x_train,y_train,scoring='accuracy',cv=13).mean())
c.append(cross_val_score(clf_str,x_train,y_train,scoring='accuracy',cv=13).mean())
c.append(cross_val_score(rf,x_train,y_train,scoring='accuracy',cv=13).mean())
print(c)

[0.7690379836933803, 0.7694975346049492, 0.768716081820258]


# **DL**

In [ ]:
# importing libraries for DL
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn import decomposition as decom
from keras.metrics import Precision, Recall

In [ ]:
#x = pd.concat([aac,dpc,struct_pc],axis=1) # combined featues of amino acid composition, dipeptide composition and physio-chemical properties
#x = aac.copy()
x = dpc.copy() # dipeptide composition
#pca decomposition for extracting relevant features
# pca = decom.PCA(n_components = 3)
# pca.fit(x)
# x = pca.transform(x)

# x = struct_pc.copy() # physio-chemical properties

y = target['Target']

In [ ]:
x # displaying the dipeptide features

DPC1_AA  DPC1_AC  DPC1_AD  DPC1_AE  DPC1_AF  DPC1_AG  DPC1_AH  DPC1_AI  \
0          0.0      0.0     0.00      0.0      0.0      0.0      0.0      0.0   
1          0.0      0.0     0.00      0.0      0.0      0.0      0.0      0.0   
2          0.0      0.0     7.14      0.0      0.0      0.0      0.0      0.0   
3          0.0      0.0     0.00      0.0      0.0      0.0      0.0      0.0   
4          0.0      0.0     7.14      0.0      0.0      0.0      0.0      0.0   
...        ...      ...      ...      ...      ...      ...      ...      ...   
62164      0.0      0.0     0.00      0.0      0.0      0.0      0.0      0.0   
62165      0.0      0.0     0.00      0.0      0.0      0.0      0.0      0.0   
62166      0.0      0.0     0.00      0.0      0.0      0.0      0.0      0.0   
62167      0.0      0.0     0.00      0.0      0.0      0.0      0.0      0.0   
62168      0.0      0.0     0.00      0.0      0.0      0.0      0.0      0.0   

       DPC1_AK  DPC1_AL  ...  DPC1_YM  DPC1_YN  DPC1_YP  DPC1_YQ  DPC1_YR  \
0          0.0     0.00  ...      0.0      0.0      0.0      0.0      0.0   
1          0.0     0.00  ...      0.0      0.0      0.0      0.0      0.0   
2          0.0     0.00  ...      0.0      0.0      0.0      0.0      0.0   
3          0.0     0.00  ...      0.0      0.0      0.0      0.0      0.0   
4          0.0     0.00  ...      0.0      0.0      0.0      0.0      0.0   
...        ...      ...  ...      ...      ...      ...      ...      ...   
62164      0.0     7.14  ...      0.0      0.0      0.0      0.0      0.0   
62165      0.0     0.00  ...      0.0      0.0      0.0      0.0      0.0   
62166      0.0     0.00  ...      0.0      0.0      0.0      0.0      0.0   
62167      0.0     0.00  ...      0.0      0.0      0.0      0.0      0.0   
62168      0.0    14.29  ...      0.0      0.0      0.0      0.0      0.0   

       DPC1_YS  DPC1_YT  DPC1_YV  DPC1_YW  DPC1_YY  
0         0.00      0.0      0.0      0.0      0.0  
1         0.00      0.0      0.0      0.0      0.0  
2         0.00      0.0      0.0      0.0      0.0  
3         0.00      0.0      0.0      0.0      0.0  
4         0.00      0.0      0.0      0.0      0.0  
...        ...      ...      ...      ...      ...  
62164     0.00      0.0      0.0      0.0      0.0  
62165     0.00      0.0      0.0      0.0      0.0  
62166     0.00      0.0      0.0      0.0      0.0  
62167     7.14      0.0      0.0      0.0      0.0  
62168     0.00      0.0      0.0      0.0      0.0  

[62169 rows x 400 columns]

In [ ]:
y # displaying the target

0        1
1        1
2        0
3        1
4        1
        ..
62164    0
62165    0
62166    0
62167    1
62168    0
Name: Target, Length: 62169, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42) # splitting the data into train test

In [ ]:
# creating the model
model = Sequential()
model.add(Dense(256, input_shape=(x_train.shape[1],), activation='relu'))
model.add(Dense(128, activation='tanh'))
model.add(Dense(64, activation='tanh'))
model.add(Dense(32, activation='tanh'))
model.add(Dense(16, activation='tanh'))
model.add(Dense(8, activation='tanh'))
model.add(Dense(4, activation='tanh'))
model.add(Dense(2, activation='tanh'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
# function to train model and evaluate scores
def train_model(model, opt, x_train, y_train, x_test, y_test, epoch, batch_size):
  model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy', Precision(), Recall()])
  model.fit(x_train, y_train, epochs=epoch, batch_size=batch_size)
  _, accuracy,precision,recall = model.evaluate(x_test, y_test, verbose=0)
  return accuracy,precision,recall

In [ ]:
# function to print evaluation scores
def print_score(score):
  print("Accuracy  : ", score[0])
  print("Precision : ", score[1])
  print("Recall    : ", score[2])
  f1_score = (2*score[1]*score[2])/(score[1]+score[2])
  print("F1- Score : ", f1_score)

In [ ]:
eval_met = list(train_model(model, "rmsprop", x_train, y_train, x_test, y_test, 100, 128)) # training the model

Epoch 1/100
340/340 [==============================] - 6s 9ms/step - loss: 0.0123 - accuracy: 0.9957 - precision_2: 0.9948 - recall_2: 0.9968
Epoch 2/100
340/340 [==============================] - 2s 6ms/step - loss: 0.0116 - accuracy: 0.9957 - precision_2: 0.9950 - recall_2: 0.9968
Epoch 3/100
340/340 [==============================] - 2s 5ms/step - loss: 0.0100 - accuracy: 0.9960 - precision_2: 0.9949 - recall_2: 0.9974
Epoch 4/100
340/340 [==============================] - 2s 7ms/step - loss: 0.0111 - accuracy: 0.9958 - precision_2: 0.9950 - recall_2: 0.9968
Epoch 5/100
340/340 [==============================] - 3s 8ms/step - loss: 0.0109 - accuracy: 0.9960 - precision_2: 0.9956 - recall_2: 0.9968
Epoch 6/100
340/340 [==============================] - 2s 5ms/step - loss: 0.0095 - accuracy: 0.9965 - precision_2: 0.9963 - recall_2: 0.9968
Epoch 7/100
340/340 [==============================] - 2s 5ms/step - loss: 0.0087 - accuracy: 0.9963 - precision_2: 0.9958 - recall_2: 0.9971
Epoch 

In [ ]:
print_score(eval_met) # print accuracy, precision, recall, f1-score

Accuracy  :  0.7619430422782898
Precision :  0.7550169825553894
Recall    :  0.8028038144111633
F1- Score :  0.7781774575367764
