In [ ]:
# installing and importing catboost library
!pip install catboost
from catboost import CatBoostClassifier

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.5/98.5 MB 9.0 MB/s eta 0:00:00


In [ ]:
# importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, recall_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import make_scorer, precision_score, recall_score, f1_score
from sklearn.model_selection import cross_validate
from sklearn.naive_bayes import CategoricalNB
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVC

from sklearn.metrics import accuracy_score

from sklearn import metrics as mt
import matplotlib.pyplot as plt
import warnings
import sys
warnings.filterwarnings('ignore')

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_validate, StratifiedKFold
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/rdkit_dataset.csv') # loading the dataset

In [ ]:
data # displaying the dataset

MolWt  NumRotatableBonds    TPSA  AUTOCORR2D_1  AUTOCORR2D_2  \
0      1776.113               60.0  701.14     14.729097      0.060103   
1      1738.874               57.0  832.01     14.566415      0.044381   
2      1677.925               51.0  676.94     14.402321      0.029760   
3      1710.150               59.0  667.71     14.676367      0.005836   
4      1858.098               53.0  766.93     14.709878      0.005817   
...         ...                ...     ...           ...           ...   
57230  1640.855               48.0  612.33     14.773368      0.010197   
57231  1875.308               57.0  663.32     15.220414      0.032724   
57232  1782.131               63.0  852.17     14.643091      0.010002   
57233  1794.957               54.0  860.69     14.849205      0.002266   
57234  1653.789               54.0  733.72     14.199916      0.016046   

       AUTOCORR2D_3  AUTOCORR2D_4  AUTOCORR2D_5  AUTOCORR2D_6  AUTOCORR2D_7  \
0         -2.080788      0.021793     15.138211      1776.113      1649.105   
1         -2.170827      0.016357     16.352459      1738.874      1618.922   
2         -1.806985      0.016682     16.504202      1677.925      1556.965   
3         -1.634398      0.013024     15.364407      1710.150      1577.094   
4         -2.152389      0.008452     16.384615      1858.098      1741.170   
...             ...           ...           ...           ...           ...   
57230     -1.973330      0.019602     15.623932      1640.855      1526.951   
57231     -1.771628      0.008432     15.969697      1875.308      1743.260   
57232     -1.943594      0.015273     15.480000      1782.131      1641.011   
57233     -2.057832      0.016611     17.401575      1794.957      1675.005   
57234     -2.049998      0.016359     15.991304      1653.789      1544.925   

       ...  AUTOCORR2D_182  AUTOCORR2D_183  AUTOCORR2D_184  AUTOCORR2D_185  \
0      ...             0.0             0.0             0.0             0.0   
1      ...             0.0             0.0             0.0             0.0   
2      ...             0.0             0.0             0.0             0.0   
3      ...             0.0             0.0             0.0             0.0   
4      ...             0.0             0.0             0.0             0.0   
...    ...             ...             ...             ...             ...   
57230  ...             0.0             0.0             0.0             0.0   
57231  ...             0.0             0.0             0.0             0.0   
57232  ...             0.0             0.0             0.0             0.0   
57233  ...             0.0             0.0             0.0             0.0   
57234  ...             0.0             0.0             0.0             0.0   

       AUTOCORR2D_186  AUTOCORR2D_187  AUTOCORR2D_188  AUTOCORR2D_189  \
0                 0.0             0.0             0.0             0.0   
1                 0.0             0.0             0.0             0.0   
2                 0.0             0.0             0.0             0.0   
3                 0.0             0.0             0.0             0.0   
4                 0.0             0.0             0.0             0.0   
...               ...             ...             ...             ...   
57230             0.0             0.0             0.0             0.0   
57231             0.0             0.0             0.0             0.0   
57232             0.0             0.0             0.0             0.0   
57233             0.0             0.0             0.0             1.0   
57234             0.0             0.0             0.0             0.0   

            qed  Target  
0      0.021793       0  
1      0.016357       0  
2      0.016682       0  
3      0.013024       1  
4      0.008452       1  
...         ...     ...  
57230  0.019602       1  
57231  0.008432       0  
57232  0.015273       0  
57233  0.016611       1  
57234  0.016359       1  

[57235 rows x 194 columns]

In [ ]:
data.isna().sum() # checking if data contains null value

MolWt                3
NumRotatableBonds    3
TPSA                 3
AUTOCORR2D_1         3
AUTOCORR2D_2         3
                    ..
AUTOCORR2D_187       3
AUTOCORR2D_188       3
AUTOCORR2D_189       3
qed                  3
Target               0
Length: 194, dtype: int64

In [ ]:
data.dropna(inplace=True) # removing null values

In [ ]:
data.isna().sum() # checking if data contains null value

MolWt                0
NumRotatableBonds    0
TPSA                 0
AUTOCORR2D_1         0
AUTOCORR2D_2         0
                    ..
AUTOCORR2D_187       0
AUTOCORR2D_188       0
AUTOCORR2D_189       0
qed                  0
Target               0
Length: 194, dtype: int64

In [ ]:
# scaling the data
sc = MinMaxScaler()
data = pd.DataFrame(sc.fit_transform(data))

In [ ]:
# function to calculate evaluation metrices
def metric_calculation(y_test,y_pred):
  print("Accuracy  :  ",mt.accuracy_score(y_test,y_pred))
  print("Precision :  ",mt.precision_score(y_test,y_pred))
  print("Recall    :  ",mt.recall_score(y_test,y_pred))
  print("F1-score  :  ",mt.f1_score(y_test,y_pred))
  print("Confusion matrix      : \n ",mt.confusion_matrix(y_test,y_pred))
  print("Classification report : \n",mt.classification_report(y_test,y_pred))

In [ ]:
# splitting dataset to features and target
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1) # splitting dataset to train and test

# **ML**

In [ ]:
# creating the objects of classifiers
rf = RandomForestClassifier()
mlp = MLPClassifier()
sgd = SGDClassifier()
svc = SVC()
lr = LogisticRegression()
knn = KNeighborsClassifier(n_neighbors=1)
cat = CatBoostClassifier( iterations=100, depth=14, learning_rate=0.1,verbose=False)
bgc_rf = BaggingClassifier(estimator=rf, n_estimators=20, random_state=0)
hist_gbc = HistGradientBoostingClassifier()
ada = AdaBoostClassifier(base_estimator=rf, n_estimators=10, learning_rate = 0.1)
lgbm = LGBMClassifier(random_state=5)

In [ ]:
# Random Forest
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.7360512521840419
Precision :   0.7297462176671548
Recall    :   0.7207760906242469
F1-score  :   0.7252334182126835
Confusion matrix      : 
  [[6657 2215]
 [2317 5981]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.74      0.75      0.75      8872
         1.0       0.73      0.72      0.73      8298

    accuracy                           0.74     17170
   macro avg       0.74      0.74      0.74     17170
weighted avg       0.74      0.74      0.74     17170



In [ ]:
# MLP classifier
mlp.fit(x_train,y_train)
y_pred = mlp.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6734420500873617
Precision :   0.6460119370591427
Recall    :   0.7174017835623042
F1-score  :   0.6798378347513276
Confusion matrix      : 
  [[5610 3262]
 [2345 5953]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.71      0.63      0.67      8872
         1.0       0.65      0.72      0.68      8298

    accuracy                           0.67     17170
   macro avg       0.68      0.67      0.67     17170
weighted avg       0.68      0.67      0.67     17170



In [ ]:
# SGD Classifier
sgd.fit(x_train,y_train)
y_pred = sgd.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6470588235294118
Precision :   0.639179104477612
Recall    :   0.6193058568329718
F1-score  :   0.6290855673889093
Confusion matrix      : 
  [[5971 2901]
 [3159 5139]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.65      0.67      0.66      8872
         1.0       0.64      0.62      0.63      8298

    accuracy                           0.65     17170
   macro avg       0.65      0.65      0.65     17170
weighted avg       0.65      0.65      0.65     17170



In [ ]:
# Support Vector Machine
svc.fit(x_train,y_train)
y_pred = svc.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.666045428072219
Precision :   0.650293083235639
Recall    :   0.6684743311641359
F1-score  :   0.6592583788923224
Confusion matrix      : 
  [[5889 2983]
 [2751 5547]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.68      0.66      0.67      8872
         1.0       0.65      0.67      0.66      8298

    accuracy                           0.67     17170
   macro avg       0.67      0.67      0.67     17170
weighted avg       0.67      0.67      0.67     17170



In [ ]:
# Logistic Regression
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6458357600465929
Precision :   0.638892369377271
Recall    :   0.6144854181730538
F1-score  :   0.6264512562196695
Confusion matrix      : 
  [[5990 2882]
 [3199 5099]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.65      0.68      0.66      8872
         1.0       0.64      0.61      0.63      8298

    accuracy                           0.65     17170
   macro avg       0.65      0.64      0.64     17170
weighted avg       0.65      0.65      0.65     17170



In [ ]:
# K Nearest Neighbour
for k in range(1, 10,2):
  knn = KNeighborsClassifier(n_neighbors=k)
  knn.fit(x_train,y_train)
  y_pred = knn.predict(x_test)
  print("k = ", k)
  metric_calculation(y_test,y_pred)

k =  1
Accuracy  :   0.6791496796738498
Precision :   0.660934795152914
Recall    :   0.6901663051337672
F1-score  :   0.6752343335494901
Confusion matrix      : 
  [[5934 2938]
 [2571 5727]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.70      0.67      0.68      8872
         1.0       0.66      0.69      0.68      8298

    accuracy                           0.68     17170
   macro avg       0.68      0.68      0.68     17170
weighted avg       0.68      0.68      0.68     17170

k =  3
Accuracy  :   0.6587652882935352
Precision :   0.642116303461135
Recall    :   0.6640154254037117
F1-score  :   0.6528822797559096
Confusion matrix      : 
  [[5801 3071]
 [2788 5510]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.68      0.65      0.66      8872
         1.0       0.64      0.66      0.65      8298

    accuracy                           0.66     17170
   macro avg       

In [ ]:
# Catboost Classifier
cat.fit(x_train,y_train)
y_pred = cat.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.728246942341293
Precision :   0.7178502879078695
Recall    :   0.7211376235237407
F1-score  :   0.7194902007935554
Confusion matrix      : 
  [[6520 2352]
 [2314 5984]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.74      0.73      0.74      8872
         1.0       0.72      0.72      0.72      8298

    accuracy                           0.73     17170
   macro avg       0.73      0.73      0.73     17170
weighted avg       0.73      0.73      0.73     17170



In [ ]:
# Bagging Classifier
bgc_rf.fit(x_train,y_train)
y_pred = bgc_rf.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.7336633663366336
Precision :   0.7174547577349679
Recall    :   0.7405398891299109
F1-score  :   0.7288145644310028
Confusion matrix      : 
  [[6452 2420]
 [2153 6145]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.75      0.73      0.74      8872
         1.0       0.72      0.74      0.73      8298

    accuracy                           0.73     17170
   macro avg       0.73      0.73      0.73     17170
weighted avg       0.73      0.73      0.73     17170



In [ ]:
hist_gbc.fit(x_train,y_train)
y_pred = hist_gbc.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6825859056493885
Precision :   0.6650057937427578
Recall    :   0.6916124367317426
F1-score  :   0.6780482041587901
Confusion matrix      : 
  [[5981 2891]
 [2559 5739]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.70      0.67      0.69      8872
         1.0       0.67      0.69      0.68      8298

    accuracy                           0.68     17170
   macro avg       0.68      0.68      0.68     17170
weighted avg       0.68      0.68      0.68     17170



In [ ]:
# Adaboost Classifier
ada.fit(x_train,y_train)
y_pred = ada.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.7410017472335468
Precision :   0.7294173716192065
Recall    :   0.737768136900458
F1-score  :   0.7335689892756577
Confusion matrix      : 
  [[6601 2271]
 [2176 6122]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.75      0.74      0.75      8872
         1.0       0.73      0.74      0.73      8298

    accuracy                           0.74     17170
   macro avg       0.74      0.74      0.74     17170
weighted avg       0.74      0.74      0.74     17170



In [ ]:
# LGBM
lgbm.fit(x_train,y_train)
y_pred = lgbm.predict(x_test)
metric_calculation(y_test,y_pred)

[LightGBM] [Info] Number of positive: 18934, number of negative: 21128
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.036570 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 21824
[LightGBM] [Info] Number of data points in the train set: 40062, number of used features: 139
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.472617 -> initscore=-0.109640
[LightGBM] [Info] Start training from score -0.109640
Accuracy  :   0.6885264997087944
Precision :   0.6714318921431892
Recall    :   0.6961918534586647
F1-score  :   0.6835877410957283
Confusion matrix      : 
  [[6045 2827]
 [2521 5777]]
Classification report : 
               precision    recall  f1-score   support

         0.0       0.71      0.68      0.69      8872
         1.0       0.67      0.70      0.68      8298

    accuracy                           0.69     17170
   macro a

DL

In [ ]:
# importing libraries for DL
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn import decomposition as decom
from keras.metrics import Precision, Recall
import tensorflow as tf

In [ ]:
# splitting dataset into train, validation and test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

In [ ]:
# function to create DL Model
def create_dl_model(x_train):
  model = Sequential()
  model.add(Dense(256, input_shape=(x_train.shape[1],), activation='relu'))
  model.add(Dense(128, activation='tanh'))
  model.add(Dense(64, activation='tanh'))
  model.add(Dense(32, activation='tanh'))
  model.add(Dense(16, activation='tanh'))
  model.add(Dense(8, activation='tanh'))
  model.add(Dense(4, activation='tanh'))
  model.add(Dense(2, activation='tanh'))
  model.add(Dense(1, activation='sigmoid'))
  return model

In [ ]:
# function to compile and evaluate model
def train_model(model, opt, x_train, y_train, x_val, y_val, x_test, y_test, epoch, batch_size):
  model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy', Precision(), Recall()])
  early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
  hist = model.fit(x_train, y_train, epochs=epoch, batch_size=batch_size, validation_data=(x_val, y_val), callbacks=[early_stopping])
  _, accuracy,precision,recall = model.evaluate(x_test, y_test, verbose=0)
  return accuracy,precision,recall, hist

In [ ]:
model = create_dl_model(x_train) # create model

In [ ]:
# function to print evaluation metrices
def print_score(score):
  print("Accuracy  : ", score[0])
  print("Precision : ", score[1])
  print("Recall    : ", score[2])
  f1_score = (2*score[1]*score[2])/(score[1]+score[2])
  print("F1- Score : ", f1_score)

In [ ]:
# training model and evaluating scores with different batch size and optimizers and iterations

In [ ]:
batches = [64, 128, 256, 512]
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adam", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 6s 7ms/step - loss: 0.6543 - accuracy: 0.6157 - precision: 0.5914 - recall: 0.6395 - val_loss: 0.6429 - val_accuracy: 0.6386 - val_precision: 0.6181 - val_recall: 0.5983
Epoch 2/100
501/501 [==============================] - 4s 8ms/step - loss: 0.6347 - accuracy: 0.6439 - precision: 0.6147 - recall: 0.6876 - val_loss: 0.6250 - val_accuracy: 0.6587 - val_precision: 0.6170 - val_recall: 0.7158
Epoch 3/100
501/501 [==============================] - 3s 6ms/step - loss: 0.6281 - accuracy: 0.6498 - precision: 0.6220 - recall: 0.6854 - val_loss: 0.6232 - val_accuracy: 0.6587 - val_precision: 0.6115 - val_recall: 0.7443
Epoch 4/100
501/501 [==============================] - 3s 5ms/step - loss: 0.6250 - accuracy: 0.6511 - precision: 0.6254 - recall: 0.6771 - val_loss: 0.6203 - val_accuracy: 0.6571 - val_precision: 0.6224 - val_recall: 0.6811
Epoch 5/100
501/501 [==============================] - 3s 5ms/step - loss: 0.6217 -

In [ ]:
batches = [64, 128, 256, 512]
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adadelta", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 6s 7ms/step - loss: 0.5719 - accuracy: 0.6924 - precision_4: 0.6772 - recall_4: 0.6839 - val_loss: 0.6029 - val_accuracy: 0.6673 - val_precision_4: 0.6364 - val_recall_4: 0.6761
Epoch 2/100
501/501 [==============================] - 2s 4ms/step - loss: 0.5716 - accuracy: 0.6921 - precision_4: 0.6755 - recall_4: 0.6872 - val_loss: 0.6031 - val_accuracy: 0.6665 - val_precision_4: 0.6348 - val_recall_4: 0.6785
Epoch 3/100
501/501 [==============================] - 2s 4ms/step - loss: 0.5714 - accuracy: 0.6923 - precision_4: 0.6750 - recall_4: 0.6895 - val_loss: 0.6032 - val_accuracy: 0.6657 - val_precision_4: 0.6335 - val_recall_4: 0.6795
Epoch 4/100
501/501 [==============================] - 2s 4ms/step - loss: 0.5711 - accuracy: 0.6925 - precision_4: 0.6742 - recall_4: 0.6926 - val_loss: 0.6033 - val_accuracy: 0.6658 - val_precision_4: 0.6332 - val_recall_4: 0.6814
Epoch 5/100
501/501 [==============================

In [ ]:
batches = [64, 128, 256, 512]
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "rmsprop", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 7s 9ms/step - loss: 0.5889 - accuracy: 0.6808 - precision_8: 0.6619 - recall_8: 0.6818 - val_loss: 0.6259 - val_accuracy: 0.6473 - val_precision_8: 0.6595 - val_recall_8: 0.5112
Epoch 2/100
501/501 [==============================] - 3s 5ms/step - loss: 0.5892 - accuracy: 0.6812 - precision_8: 0.6615 - recall_8: 0.6848 - val_loss: 0.6199 - val_accuracy: 0.6603 - val_precision_8: 0.6285 - val_recall_8: 0.6723
Epoch 3/100
501/501 [==============================] - 2s 4ms/step - loss: 0.5884 - accuracy: 0.6815 - precision_8: 0.6621 - recall_8: 0.6844 - val_loss: 0.6108 - val_accuracy: 0.6650 - val_precision_8: 0.6202 - val_recall_8: 0.7352
Epoch 4/100
501/501 [==============================] - 2s 4ms/step - loss: 0.5882 - accuracy: 0.6830 - precision_8: 0.6631 - recall_8: 0.6876 - val_loss: 0.6109 - val_accuracy: 0.6607 - val_precision_8: 0.6122 - val_recall_8: 0.7523
Epoch 5/100
501/501 [==============================

# **LSTM**

In [ ]:
# function to create LSTM Model
def create_model(data):
  model = tf.keras.Sequential([
      tf.keras.layers.LSTM(64, input_shape=(1, data.shape[2]), return_sequences=True),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.LSTM(64, return_sequences=True),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.LSTM(32),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(16, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(8, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.001)),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(1, activation='sigmoid'),
  ])
  return model

In [ ]:
# function to split data into train, test and val and preprocess it
def split_data(x, y):
  x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
  x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)
  x_train = x_train.reshape(x_train.shape[0], 1, x_train.shape[1])
  x_val = x_val.reshape(x_val.shape[0], 1, x_val.shape[1])
  x_test = x_test.reshape(x_test.shape[0], 1, x_test.shape[1])
  return x_train, x_val, x_test, y_train, y_val, y_test

In [ ]:
# def evaluate_score(model, x_test, y_test):
#   _, acc, prec, rec = model.evaluate(x_test, y_test)
#   try:
#     f1_score = (2*prec*rec)/(prec+rec)
#   except:
#     f1_score = 0
#   print("Accuracy  :", acc)
#   print("Precision :", prec)
#   print("Recall    :", rec)
#   print("F1-Score  :", f1_score)

In [ ]:
# splitting dataset and creating model
batches = [64, 128, 256, 512]
x_train, x_val, x_test, y_train, y_val, y_test = split_data(x.values, y.values)
model = create_model(x_train)

In [ ]:
# training model and evaluating scores with different batch size and optimizers and iterations

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adam", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 13s 13ms/step - loss: 0.6790 - accuracy: 0.5906 - precision_12: 0.5930 - recall_12: 0.4629 - val_loss: 0.6531 - val_accuracy: 0.6262 - val_precision_12: 0.5794 - val_recall_12: 0.7379
Epoch 2/100
501/501 [==============================] - 4s 8ms/step - loss: 0.6539 - accuracy: 0.6308 - precision_12: 0.6107 - recall_12: 0.6321 - val_loss: 0.6440 - val_accuracy: 0.6295 - val_precision_12: 0.6267 - val_recall_12: 0.5173
Epoch 3/100
501/501 [==============================] - 5s 10ms/step - loss: 0.6458 - accuracy: 0.6396 - precision_12: 0.6151 - recall_12: 0.6612 - val_loss: 0.6351 - val_accuracy: 0.6524 - val_precision_12: 0.6035 - val_recall_12: 0.7525
Epoch 4/100
501/501 [==============================] - 4s 8ms/step - loss: 0.6389 - accuracy: 0.6469 - precision_12: 0.6191 - recall_12: 0.6828 - val_loss: 0.6260 - val_accuracy: 0.6604 - val_precision_12: 0.6190 - val_recall_12: 0.7158
Epoch 5/100
501/501 [===========

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adadelta", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 13s 13ms/step - loss: 0.5779 - accuracy: 0.6973 - precision_16: 0.6748 - recall_16: 0.7102 - val_loss: 0.5977 - val_accuracy: 0.6752 - val_precision_16: 0.6417 - val_recall_16: 0.6942
Epoch 2/100
501/501 [==============================] - 5s 9ms/step - loss: 0.5772 - accuracy: 0.6983 - precision_16: 0.6751 - recall_16: 0.7137 - val_loss: 0.5977 - val_accuracy: 0.6757 - val_precision_16: 0.6421 - val_recall_16: 0.6950
Epoch 3/100
501/501 [==============================] - 4s 8ms/step - loss: 0.5783 - accuracy: 0.6969 - precision_16: 0.6741 - recall_16: 0.7108 - val_loss: 0.5977 - val_accuracy: 0.6755 - val_precision_16: 0.6423 - val_recall_16: 0.6939
Epoch 4/100
501/501 [==============================] - 6s 11ms/step - loss: 0.5784 - accuracy: 0.6959 - precision_16: 0.6730 - recall_16: 0.7102 - val_loss: 0.5977 - val_accuracy: 0.6764 - val_precision_16: 0.6430 - val_recall_16: 0.6953
Epoch 5/100
501/501 [===========

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "rmsprop", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 12s 14ms/step - loss: 0.5848 - accuracy: 0.6905 - precision_20: 0.6662 - recall_20: 0.7091 - val_loss: 0.6014 - val_accuracy: 0.6747 - val_precision_20: 0.6510 - val_recall_20: 0.6585
Epoch 2/100
501/501 [==============================] - 4s 7ms/step - loss: 0.5827 - accuracy: 0.6933 - precision_20: 0.6712 - recall_20: 0.7051 - val_loss: 0.6034 - val_accuracy: 0.6655 - val_precision_20: 0.6172 - val_recall_20: 0.7533
Epoch 3/100
501/501 [==============================] - 4s 8ms/step - loss: 0.5863 - accuracy: 0.6918 - precision_20: 0.6678 - recall_20: 0.7096 - val_loss: 0.6014 - val_accuracy: 0.6750 - val_precision_20: 0.6461 - val_recall_20: 0.6774
Epoch 4/100
501/501 [==============================] - 5s 10ms/step - loss: 0.5859 - accuracy: 0.6942 - precision_20: 0.6715 - recall_20: 0.7078 - val_loss: 0.6014 - val_accuracy: 0.6738 - val_precision_20: 0.6349 - val_recall_20: 0.7147
Epoch 5/100
501/501 [===========

# **BiLSTM**

In [ ]:
# function to create BiLSTM model
def create_model_BiLSTM(data):
  model = tf.keras.Sequential([
      tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64, return_sequences=True), input_shape=(1, x_train.shape[2])),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64, return_sequences=True)),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32)),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(16, activation='relu'),
      tf.keras.layers.Dropout(0.2),
      tf.keras.layers.Dense(1, activation='sigmoid')
  ])
  return model

In [ ]:
model = create_model_BiLSTM(x_train) # calling model for training

In [ ]:
# training model and evaluating scores with different batch size and optimizers and iterations

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adam", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 22s 19ms/step - loss: 0.6593 - accuracy: 0.6086 - precision_24: 0.5982 - recall_24: 0.5570 - val_loss: 0.6433 - val_accuracy: 0.6292 - val_precision_24: 0.6062 - val_recall_24: 0.5951
Epoch 2/100
501/501 [==============================] - 7s 13ms/step - loss: 0.6432 - accuracy: 0.6356 - precision_24: 0.6139 - recall_24: 0.6447 - val_loss: 0.6425 - val_accuracy: 0.6362 - val_precision_24: 0.5810 - val_recall_24: 0.8013
Epoch 3/100
501/501 [==============================] - 8s 16ms/step - loss: 0.6332 - accuracy: 0.6461 - precision_24: 0.6189 - recall_24: 0.6796 - val_loss: 0.6257 - val_accuracy: 0.6534 - val_precision_24: 0.6294 - val_recall_24: 0.6329
Epoch 4/100
501/501 [==============================] - 6s 13ms/step - loss: 0.6273 - accuracy: 0.6521 - precision_24: 0.6197 - recall_24: 0.7083 - val_loss: 0.6203 - val_accuracy: 0.6561 - val_precision_24: 0.6083 - val_recall_24: 0.7464
Epoch 5/100
501/501 [=========

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adadelta", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 24s 22ms/step - loss: 0.5792 - accuracy: 0.6886 - precision_28: 0.6729 - recall_28: 0.6806 - val_loss: 0.5986 - val_accuracy: 0.6720 - val_precision_28: 0.6419 - val_recall_28: 0.6785
Epoch 2/100
501/501 [==============================] - 8s 16ms/step - loss: 0.5780 - accuracy: 0.6885 - precision_28: 0.6702 - recall_28: 0.6885 - val_loss: 0.5985 - val_accuracy: 0.6724 - val_precision_28: 0.6411 - val_recall_28: 0.6833
Epoch 3/100
501/501 [==============================] - 8s 15ms/step - loss: 0.5782 - accuracy: 0.6911 - precision_28: 0.6718 - recall_28: 0.6943 - val_loss: 0.5984 - val_accuracy: 0.6713 - val_precision_28: 0.6390 - val_recall_28: 0.6857
Epoch 4/100
501/501 [==============================] - 9s 17ms/step - loss: 0.5776 - accuracy: 0.6894 - precision_28: 0.6696 - recall_28: 0.6939 - val_loss: 0.5984 - val_accuracy: 0.6714 - val_precision_28: 0.6382 - val_recall_28: 0.6894
Epoch 5/100
501/501 [=========

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "rmsprop", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 22s 19ms/step - loss: 0.5870 - accuracy: 0.6824 - precision_32: 0.6588 - recall_32: 0.6985 - val_loss: 0.6055 - val_accuracy: 0.6669 - val_precision_32: 0.6322 - val_recall_32: 0.6910
Epoch 2/100
501/501 [==============================] - 6s 12ms/step - loss: 0.5890 - accuracy: 0.6812 - precision_32: 0.6553 - recall_32: 0.7055 - val_loss: 0.6003 - val_accuracy: 0.6739 - val_precision_32: 0.6414 - val_recall_32: 0.6894
Epoch 3/100
501/501 [==============================] - 8s 15ms/step - loss: 0.5874 - accuracy: 0.6839 - precision_32: 0.6588 - recall_32: 0.7054 - val_loss: 0.6023 - val_accuracy: 0.6698 - val_precision_32: 0.6362 - val_recall_32: 0.6894
Epoch 4/100
501/501 [==============================] - 6s 12ms/step - loss: 0.5856 - accuracy: 0.6851 - precision_32: 0.6611 - recall_32: 0.7029 - val_loss: 0.6004 - val_accuracy: 0.6703 - val_precision_32: 0.6379 - val_recall_32: 0.6851
Epoch 5/100
501/501 [=========

# **Combination of rdkit, dpc and aac dataset**

In [ ]:
# loading dataset
aac = pd.read_csv("/content/drive/MyDrive/AAC_feature.csv")
dpc = pd.read_csv("/content/drive/MyDrive/DPC_feature.csv")
target = pd.read_csv("/content/drive/MyDrive/target.csv")

In [ ]:
# scaling the dataset
aac = pd.DataFrame(sc.fit_transform(aac))
dpc = pd.DataFrame(sc.fit_transform(dpc))

In [ ]:
aac # displaying the data

0         1         2         3        4         5         6   \
0      0.090959  0.000000  0.111167  0.100045  0.00000  0.166625  0.000000   
1      0.272740  0.000000  0.000000  0.000000  0.00000  0.083375  0.000000   
2      0.272740  0.000000  0.111167  0.100045  0.20012  0.083375  0.000000   
3      0.181781  0.000000  0.111167  0.199940  0.00000  0.000000  0.000000   
4      0.272740  0.000000  0.111167  0.000000  0.00000  0.083375  0.000000   
...         ...       ...       ...       ...      ...       ...       ...   
62164  0.090959  0.142918  0.000000  0.000000  0.00000  0.166625  0.142918   
62165  0.181781  0.142918  0.111167  0.100045  0.00000  0.000000  0.000000   
62166  0.000000  0.000000  0.000000  0.100045  0.00000  0.250000  0.285622   
62167  0.000000  0.000000  0.222167  0.100045  0.00000  0.083375  0.000000   
62168  0.181781  0.000000  0.000000  0.000000  0.20012  0.083375  0.000000   

            7         8         9        10       11        12        13  \
0      0.00000  0.125070  0.125070  0.20012  0.00000  0.000000  0.142918   
1      0.16675  0.249953  0.000000  0.20012  0.00000  0.000000  0.142918   
2      0.00000  0.249953  0.125070  0.00000  0.16675  0.000000  0.142918   
3      0.16675  0.249953  0.249953  0.00000  0.00000  0.000000  0.000000   
4      0.00000  0.000000  0.125070  0.00000  0.16675  0.000000  0.000000   
...        ...       ...       ...      ...      ...       ...       ...   
62164  0.00000  0.125070  0.125070  0.00000  0.00000  0.199940  0.000000   
62165  0.16675  0.000000  0.375023  0.00000  0.00000  0.100045  0.000000   
62166  0.16675  0.000000  0.000000  0.00000  0.00000  0.199940  0.142918   
62167  0.16675  0.125070  0.249953  0.00000  0.33325  0.000000  0.000000   
62168  0.00000  0.125070  0.500094  0.00000  0.00000  0.100045  0.000000   

             14      15        16       17      18        19  
0      0.181781  0.0000  0.142827  0.33325  0.0000  0.000000  
1      0.181781  0.0667  0.142827  0.16675  0.0000  0.000000  
2      0.090959  0.0667  0.000000  0.16675  0.0000  0.000000  
3      0.181781  0.0667  0.142827  0.00000  0.0000  0.000000  
4      0.272740  0.0667  0.000000  0.50000  0.0000  0.142918  
...         ...     ...       ...      ...     ...       ...  
62164  0.090959  0.2000  0.000000  0.33325  0.0000  0.000000  
62165  0.181781  0.0667  0.071467  0.16675  0.0000  0.000000  
62166  0.000000  0.0667  0.071467  0.33325  0.0000  0.142918  
62167  0.000000  0.0667  0.071467  0.16675  0.0000  0.285622  
62168  0.090959  0.0667  0.071467  0.00000  0.3335  0.142918  

[62169 rows x 20 columns]

In [ ]:
# merging the rdkit features and dipeptide composition features
combined_data = pd.concat([dpc, data, target], axis=1)
combined_data

0    1        2    3    4    5    6    7    8         9  ...  185  \
0      0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  0.0   
1      0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  0.0   
2      0.0  0.0  0.49965  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  0.0   
3      0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  0.0   
4      0.0  0.0  0.49965  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  0.0   
...    ...  ...      ...  ...  ...  ...  ...  ...  ...       ...  ...  ...   
62164  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  0.249912  ...  NaN   
62165  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  NaN   
62166  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  NaN   
62167  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  NaN   
62168  0.0  0.0  0.00000  0.0  0.0  0.0  0.0  0.0  0.0  0.500175  ...  NaN   

       186  187  188  189  190  191       192  193  Target  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.401391  0.0       1  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.250889  0.0       1  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.259876  0.0       0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.158587  1.0       1  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.031997  1.0       1  
...    ...  ...  ...  ...  ...  ...       ...  ...     ...  
62164  NaN  NaN  NaN  NaN  NaN  NaN       NaN  NaN       0  
62165  NaN  NaN  NaN  NaN  NaN  NaN       NaN  NaN       0  
62166  NaN  NaN  NaN  NaN  NaN  NaN       NaN  NaN       0  
62167  NaN  NaN  NaN  NaN  NaN  NaN       NaN  NaN       1  
62168  NaN  NaN  NaN  NaN  NaN  NaN       NaN  NaN       0  

[62169 rows x 595 columns]

In [ ]:
# removing null values
combined_data.dropna(inplace=True)
combined_data

0    1        2    3    4         5    6    7    8    9  ...  185  \
0      0.0  0.0  0.00000  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...  0.0   
1      0.0  0.0  0.00000  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...  0.0   
2      0.0  0.0  0.49965  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...  0.0   
3      0.0  0.0  0.00000  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...  0.0   
4      0.0  0.0  0.49965  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...  0.0   
...    ...  ...      ...  ...  ...       ...  ...  ...  ...  ...  ...  ...   
57227  0.0  0.0  0.00000  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...  0.0   
57228  0.0  0.0  0.00000  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...  0.0   
57229  0.0  0.0  0.00000  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...  0.0   
57230  0.0  0.0  0.00000  0.0  0.0  0.000000  0.0  0.0  0.0  0.0  ...  0.0   
57231  0.0  0.0  0.00000  0.0  0.0  0.333178  0.0  0.0  0.0  0.0  ...  0.0   

       186  187  188  189  190   191       192  193  Target  
0      0.0  0.0  0.0  0.0  0.0  0.00  0.401391  0.0       1  
1      0.0  0.0  0.0  0.0  0.0  0.00  0.250889  0.0       1  
2      0.0  0.0  0.0  0.0  0.0  0.00  0.259876  0.0       0  
3      0.0  0.0  0.0  0.0  0.0  0.00  0.158587  1.0       1  
4      0.0  0.0  0.0  0.0  0.0  0.00  0.031997  1.0       1  
...    ...  ...  ...  ...  ...   ...       ...  ...     ...  
57227  0.0  0.0  0.0  0.0  0.0  0.00  0.340727  1.0       0  
57228  0.0  0.0  0.0  0.0  0.0  0.00  0.031450  0.0       0  
57229  0.0  0.0  0.0  0.0  0.0  0.00  0.220864  0.0       1  
57230  0.0  0.0  0.0  0.0  0.0  0.25  0.257904  1.0       0  
57231  0.0  0.0  0.0  0.0  0.0  0.00  0.250949  1.0       0  

[57232 rows x 595 columns]

In [ ]:
# splitting data into features and target
x = combined_data.iloc[:,:-1]
y = combined_data.iloc[:,-1]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1) # splitting data into trai test data

In [ ]:
# applying random forest classifier
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6755387303436226
Precision :   0.6752314574014355
Recall    :   0.726062639821029
F1-score  :   0.6997251118417507
Confusion matrix      : 
  [[5108 3122]
 [2449 6491]]
Classification report : 
               precision    recall  f1-score   support

           0       0.68      0.62      0.65      8230
           1       0.68      0.73      0.70      8940

    accuracy                           0.68     17170
   macro avg       0.68      0.67      0.67     17170
weighted avg       0.68      0.68      0.67     17170



In [ ]:
# applying MLP classifier
mlp.fit(x_train,y_train)
y_pred = mlp.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.7135701805474665
Precision :   0.7199737475388318
Recall    :   0.736241610738255
F1-score  :   0.7280168122995244
Confusion matrix      : 
  [[5670 2560]
 [2358 6582]]
Classification report : 
               precision    recall  f1-score   support

           0       0.71      0.69      0.70      8230
           1       0.72      0.74      0.73      8940

    accuracy                           0.71     17170
   macro avg       0.71      0.71      0.71     17170
weighted avg       0.71      0.71      0.71     17170



In [ ]:
# applying stochastic gradient classifier classifier
sgd.fit(x_train,y_train)
y_pred = sgd.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6739662201514269
Precision :   0.6603954693799193
Recall    :   0.7695749440715883
F1-score  :   0.7108172331852464
Confusion matrix      : 
  [[4692 3538]
 [2060 6880]]
Classification report : 
               precision    recall  f1-score   support

           0       0.69      0.57      0.63      8230
           1       0.66      0.77      0.71      8940

    accuracy                           0.67     17170
   macro avg       0.68      0.67      0.67     17170
weighted avg       0.68      0.67      0.67     17170



In [ ]:
# applying SVM classifier
svc.fit(x_train,y_train)
y_pred = svc.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6842166569598136
Precision :   0.6792702812882185
Recall    :   0.7455257270693513
F1-score  :   0.7108575085324231
Confusion matrix      : 
  [[5083 3147]
 [2275 6665]]
Classification report : 
               precision    recall  f1-score   support

           0       0.69      0.62      0.65      8230
           1       0.68      0.75      0.71      8940

    accuracy                           0.68     17170
   macro avg       0.69      0.68      0.68     17170
weighted avg       0.68      0.68      0.68     17170



In [ ]:
# applying Logistic regression classifier
lr.fit(x_train,y_train)
y_pred = lr.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6725101921956902
Precision :   0.6749288049783778
Recall    :   0.7157718120805369
F1-score  :   0.6947505564301611
Confusion matrix      : 
  [[5148 3082]
 [2541 6399]]
Classification report : 
               precision    recall  f1-score   support

           0       0.67      0.63      0.65      8230
           1       0.67      0.72      0.69      8940

    accuracy                           0.67     17170
   macro avg       0.67      0.67      0.67     17170
weighted avg       0.67      0.67      0.67     17170



In [ ]:
# applying KNN classifier with diffenet values of k
for k in range(1, 10,2):
  knn = KNeighborsClassifier(n_neighbors=k)
  knn.fit(x_train,y_train)
  y_pred = knn.predict(x_test)
  print("k = ", k)
  metric_calculation(y_test,y_pred)

k =  1
Accuracy  :   0.5801397786837508
Precision :   0.6103531811806706
Recall    :   0.5354586129753915
F1-score  :   0.5704582017517726
Confusion matrix      : 
  [[5174 3056]
 [4153 4787]]
Classification report : 
               precision    recall  f1-score   support

           0       0.55      0.63      0.59      8230
           1       0.61      0.54      0.57      8940

    accuracy                           0.58     17170
   macro avg       0.58      0.58      0.58     17170
weighted avg       0.58      0.58      0.58     17170

k =  3
Accuracy  :   0.5675596971461853
Precision :   0.6077065263756576
Recall    :   0.47807606263982105
F1-score  :   0.5351530708069868
Confusion matrix      : 
  [[5471 2759]
 [4666 4274]]
Classification report : 
               precision    recall  f1-score   support

           0       0.54      0.66      0.60      8230
           1       0.61      0.48      0.54      8940

    accuracy                           0.57     17170
   macro avg    

In [ ]:
# applying bagging classifier
bgc_rf.fit(x_train,y_train)
y_pred = bgc_rf.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6912638322655795
Precision :   0.679632737683878
Recall    :   0.7700223713646532
F1-score  :   0.7220095442865383
Confusion matrix      : 
  [[4985 3245]
 [2056 6884]]
Classification report : 
               precision    recall  f1-score   support

           0       0.71      0.61      0.65      8230
           1       0.68      0.77      0.72      8940

    accuracy                           0.69     17170
   macro avg       0.69      0.69      0.69     17170
weighted avg       0.69      0.69      0.69     17170



In [ ]:
# applying histogram gradient boosting classifier
hist_gbc.fit(x_train,y_train)
y_pred = hist_gbc.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.6976121141525917
Precision :   0.6939557027530532
Recall    :   0.75
F1-score  :   0.7208902268573273
Confusion matrix      : 
  [[5273 2957]
 [2235 6705]]
Classification report : 
               precision    recall  f1-score   support

           0       0.70      0.64      0.67      8230
           1       0.69      0.75      0.72      8940

    accuracy                           0.70     17170
   macro avg       0.70      0.70      0.70     17170
weighted avg       0.70      0.70      0.70     17170



In [ ]:
# applying adaboost classifier
ada.fit(x_train,y_train)
y_pred = ada.predict(x_test)
metric_calculation(y_test,y_pred)

Accuracy  :   0.693185789167152
Precision :   0.690259067357513
Recall    :   0.7450782997762864
F1-score  :   0.7166218396987628
Confusion matrix      : 
  [[5241 2989]
 [2279 6661]]
Classification report : 
               precision    recall  f1-score   support

           0       0.70      0.64      0.67      8230
           1       0.69      0.75      0.72      8940

    accuracy                           0.69     17170
   macro avg       0.69      0.69      0.69     17170
weighted avg       0.69      0.69      0.69     17170



In [ ]:
# splitting data into train test and validation
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

In [ ]:
model = create_dl_model(x_train) # create dl model

In [ ]:
# training model and evaluating scores with different batch size and optimizers and iterations

In [ ]:
batches = [64, 128, 256, 512]
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adam", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 11s 15ms/step - loss: 0.6557 - accuracy: 0.6160 - precision: 0.6110 - recall: 0.7034 - val_loss: 0.6538 - val_accuracy: 0.6187 - val_precision: 0.5857 - val_recall: 0.9109
Epoch 2/100
501/501 [==============================] - 4s 8ms/step - loss: 0.6158 - accuracy: 0.6734 - precision: 0.6682 - recall: 0.7288 - val_loss: 0.6143 - val_accuracy: 0.6693 - val_precision: 0.6974 - val_recall: 0.6428
Epoch 3/100
501/501 [==============================] - 4s 8ms/step - loss: 0.6053 - accuracy: 0.6792 - precision: 0.6720 - recall: 0.7388 - val_loss: 0.6098 - val_accuracy: 0.6763 - val_precision: 0.6679 - val_recall: 0.7504
Epoch 4/100
501/501 [==============================] - 5s 11ms/step - loss: 0.5997 - accuracy: 0.6829 - precision: 0.6746 - recall: 0.7443 - val_loss: 0.6075 - val_accuracy: 0.6733 - val_precision: 0.6503 - val_recall: 0.8039
Epoch 5/100
501/501 [==============================] - 4s 7ms/step - loss: 0.593

In [ ]:
batches = [64, 128, 256, 512]
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adadelta", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 12s 18ms/step - loss: 0.4499 - accuracy: 0.8033 - precision_4: 0.7928 - recall_4: 0.8377 - val_loss: 0.6273 - val_accuracy: 0.6858 - val_precision_4: 0.6882 - val_recall_4: 0.7232
Epoch 2/100
501/501 [==============================] - 4s 8ms/step - loss: 0.4480 - accuracy: 0.8052 - precision_4: 0.7973 - recall_4: 0.8346 - val_loss: 0.6278 - val_accuracy: 0.6858 - val_precision_4: 0.6899 - val_recall_4: 0.7187
Epoch 3/100
501/501 [==============================] - 6s 11ms/step - loss: 0.4465 - accuracy: 0.8066 - precision_4: 0.7996 - recall_4: 0.8343 - val_loss: 0.6283 - val_accuracy: 0.6856 - val_precision_4: 0.6901 - val_recall_4: 0.7175
Epoch 4/100
501/501 [==============================] - 4s 9ms/step - loss: 0.4454 - accuracy: 0.8075 - precision_4: 0.8006 - recall_4: 0.8348 - val_loss: 0.6288 - val_accuracy: 0.6865 - val_precision_4: 0.6909 - val_recall_4: 0.7184
Epoch 5/100
501/501 [===========================

In [ ]:
batches = [64, 128, 256, 512]
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "rmsprop", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 8s 10ms/step - loss: 0.4938 - accuracy: 0.7690 - precision_8: 0.7624 - recall_8: 0.8022 - val_loss: 0.6118 - val_accuracy: 0.6846 - val_precision_8: 0.7186 - val_recall_8: 0.6467
Epoch 2/100
501/501 [==============================] - 4s 8ms/step - loss: 0.4841 - accuracy: 0.7780 - precision_8: 0.7721 - recall_8: 0.8083 - val_loss: 0.6181 - val_accuracy: 0.6783 - val_precision_8: 0.6564 - val_recall_8: 0.7998
Epoch 3/100
501/501 [==============================] - 5s 11ms/step - loss: 0.4754 - accuracy: 0.7856 - precision_8: 0.7763 - recall_8: 0.8210 - val_loss: 0.6437 - val_accuracy: 0.6794 - val_precision_8: 0.6504 - val_recall_8: 0.8289
Epoch 4/100
501/501 [==============================] - 4s 7ms/step - loss: 0.4631 - accuracy: 0.7930 - precision_8: 0.7845 - recall_8: 0.8254 - val_loss: 0.6385 - val_accuracy: 0.6906 - val_precision_8: 0.7312 - val_recall_8: 0.6404
Epoch 5/100
501/501 [============================

# **LSTM**

In [ ]:
# preprocessing the data and creating model
batches = [64, 128, 256, 512]
x_train, x_val, x_test, y_train, y_val, y_test = split_data(x.values, y.values)
model = create_model(x_train)

In [ ]:
# training model and evaluating scores with different batch size and optimizers and iterations

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adam", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 18s 18ms/step - loss: 0.6744 - accuracy: 0.5867 - precision_12: 0.5767 - recall_12: 0.7472 - val_loss: 0.6178 - val_accuracy: 0.6699 - val_precision_12: 0.6716 - val_recall_12: 0.7144
Epoch 2/100
501/501 [==============================] - 7s 15ms/step - loss: 0.6196 - accuracy: 0.6731 - precision_12: 0.6686 - recall_12: 0.7261 - val_loss: 0.6072 - val_accuracy: 0.6759 - val_precision_12: 0.6842 - val_recall_12: 0.6995
Epoch 3/100
501/501 [==============================] - 7s 14ms/step - loss: 0.6111 - accuracy: 0.6770 - precision_12: 0.6669 - recall_12: 0.7469 - val_loss: 0.6099 - val_accuracy: 0.6714 - val_precision_12: 0.7149 - val_recall_12: 0.6121
Epoch 4/100
501/501 [==============================] - 7s 14ms/step - loss: 0.6041 - accuracy: 0.6814 - precision_12: 0.6719 - recall_12: 0.7471 - val_loss: 0.6018 - val_accuracy: 0.6825 - val_precision_12: 0.6877 - val_recall_12: 0.7132
Epoch 5/100
501/501 [=========

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adadelta", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 17s 20ms/step - loss: 0.4446 - accuracy: 0.8097 - precision_16: 0.8091 - recall_16: 0.8260 - val_loss: 0.6189 - val_accuracy: 0.6914 - val_precision_16: 0.7000 - val_recall_16: 0.7112
Epoch 2/100
501/501 [==============================] - 7s 14ms/step - loss: 0.4442 - accuracy: 0.8093 - precision_16: 0.8069 - recall_16: 0.8286 - val_loss: 0.6197 - val_accuracy: 0.6929 - val_precision_16: 0.7008 - val_recall_16: 0.7141
Epoch 3/100
501/501 [==============================] - 8s 17ms/step - loss: 0.4447 - accuracy: 0.8109 - precision_16: 0.8096 - recall_16: 0.8281 - val_loss: 0.6205 - val_accuracy: 0.6934 - val_precision_16: 0.7014 - val_recall_16: 0.7144
Epoch 4/100
501/501 [==============================] - 7s 14ms/step - loss: 0.4447 - accuracy: 0.8093 - precision_16: 0.8071 - recall_16: 0.8283 - val_loss: 0.6213 - val_accuracy: 0.6944 - val_precision_16: 0.7021 - val_recall_16: 0.7158
Epoch 5/100
501/501 [=========

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "rmsprop", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 15s 18ms/step - loss: 0.4663 - accuracy: 0.7915 - precision_20: 0.7879 - recall_20: 0.8152 - val_loss: 0.6342 - val_accuracy: 0.6980 - val_precision_20: 0.7161 - val_recall_20: 0.6944
Epoch 2/100
501/501 [==============================] - 7s 13ms/step - loss: 0.4596 - accuracy: 0.7987 - precision_20: 0.7950 - recall_20: 0.8217 - val_loss: 0.6337 - val_accuracy: 0.6854 - val_precision_20: 0.6586 - val_recall_20: 0.8200
Epoch 3/100
501/501 [==============================] - 7s 14ms/step - loss: 0.4550 - accuracy: 0.7992 - precision_20: 0.7961 - recall_20: 0.8211 - val_loss: 0.6264 - val_accuracy: 0.6947 - val_precision_20: 0.6931 - val_recall_20: 0.7410
Epoch 4/100
501/501 [==============================] - 6s 12ms/step - loss: 0.4451 - accuracy: 0.8074 - precision_20: 0.8041 - recall_20: 0.8284 - val_loss: 0.6366 - val_accuracy: 0.6919 - val_precision_20: 0.7042 - val_recall_20: 0.7024
Epoch 5/100
501/501 [=========

# **BiLSTM**

In [ ]:
model = create_model_BiLSTM(x_train) # creating bi directional model

In [ ]:
# training model and evaluating scores with different batch size and optimizers and iterations

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adam", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 35s 29ms/step - loss: 0.6383 - accuracy: 0.6291 - precision_24: 0.6164 - recall_24: 0.7441 - val_loss: 0.6071 - val_accuracy: 0.6753 - val_precision_24: 0.6600 - val_recall_24: 0.7741
Epoch 2/100
501/501 [==============================] - 11s 21ms/step - loss: 0.6055 - accuracy: 0.6762 - precision_24: 0.6700 - recall_24: 0.7337 - val_loss: 0.6019 - val_accuracy: 0.6759 - val_precision_24: 0.6595 - val_recall_24: 0.7784
Epoch 3/100
501/501 [==============================] - 12s 24ms/step - loss: 0.5979 - accuracy: 0.6801 - precision_24: 0.6738 - recall_24: 0.7361 - val_loss: 0.5992 - val_accuracy: 0.6773 - val_precision_24: 0.6566 - val_recall_24: 0.7952
Epoch 4/100
501/501 [==============================] - 12s 25ms/step - loss: 0.5933 - accuracy: 0.6814 - precision_24: 0.6710 - recall_24: 0.7504 - val_loss: 0.5972 - val_accuracy: 0.6813 - val_precision_24: 0.6782 - val_recall_24: 0.7362
Epoch 5/100
501/501 [======

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "adadelta", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 30s 33ms/step - loss: 0.4399 - accuracy: 0.7949 - precision_28: 0.7963 - recall_28: 0.8094 - val_loss: 0.6233 - val_accuracy: 0.6997 - val_precision_28: 0.7058 - val_recall_28: 0.7244
Epoch 2/100
501/501 [==============================] - 13s 26ms/step - loss: 0.4386 - accuracy: 0.7957 - precision_28: 0.7890 - recall_28: 0.8244 - val_loss: 0.6225 - val_accuracy: 0.6994 - val_precision_28: 0.7021 - val_recall_28: 0.7326
Epoch 3/100
501/501 [==============================] - 14s 28ms/step - loss: 0.4381 - accuracy: 0.7975 - precision_28: 0.7891 - recall_28: 0.8291 - val_loss: 0.6224 - val_accuracy: 0.6999 - val_precision_28: 0.7010 - val_recall_28: 0.7372
Epoch 4/100
501/501 [==============================] - 13s 26ms/step - loss: 0.4385 - accuracy: 0.7959 - precision_28: 0.7838 - recall_28: 0.8346 - val_loss: 0.6226 - val_accuracy: 0.6999 - val_precision_28: 0.7007 - val_recall_28: 0.7379
Epoch 5/100
501/501 [======

In [ ]:
for batch in batches:
  print("Batch size = ", batch)
  eval_met = list(train_model(model, "rmsprop", x_train, y_train, x_val, y_val, x_test, y_test, 100, batch))
  print_score(eval_met)

Batch size =  64
Epoch 1/100
501/501 [==============================] - 27s 30ms/step - loss: 0.4676 - accuracy: 0.7766 - precision_32: 0.7659 - recall_32: 0.8165 - val_loss: 0.6746 - val_accuracy: 0.6870 - val_precision_32: 0.7344 - val_recall_32: 0.6234
Epoch 2/100
501/501 [==============================] - 12s 25ms/step - loss: 0.4592 - accuracy: 0.7828 - precision_32: 0.7736 - recall_32: 0.8186 - val_loss: 0.6299 - val_accuracy: 0.6909 - val_precision_32: 0.6616 - val_recall_32: 0.8301
Epoch 3/100
501/501 [==============================] - 13s 26ms/step - loss: 0.4519 - accuracy: 0.7872 - precision_32: 0.7772 - recall_32: 0.8236 - val_loss: 0.6138 - val_accuracy: 0.6929 - val_precision_32: 0.6836 - val_recall_32: 0.7619
Epoch 4/100
501/501 [==============================] - 11s 21ms/step - loss: 0.4393 - accuracy: 0.7935 - precision_32: 0.7847 - recall_32: 0.8264 - val_loss: 0.6240 - val_accuracy: 0.6954 - val_precision_32: 0.6741 - val_recall_32: 0.8015
Epoch 5/100
501/501 [======